<?php
session_start();
?>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LuxRes</title>
</head>
<link href="../css/reservation.css" rel="stylesheet">
<body>


<img src="../images/banner.jpeg" width="500px" height="200px">

<h1>Reserve your luxury car here!</h1>

<form action="../php/reserve.php" method="POST">
    <input type="text" name="username" placeholder="enter username">
    <br>
    <input type="date" name="start_date" placeholder="enter pickup date">
    <br>
    <input type="date" name="end_date" placeholder="enter drop off date">
    <br>
    <select name="car">
        <option hidden="">Choose your car</option>

        <option name="car" value="Challenger"> Challenger
        </option>
        <option name="car" value="LandRover"> Land Rover
        </option>
        <option name="car" value="Ftype"> F-type
        </option>
        <option name="car" value="Mustang"> Mustang
        </option>

    </select>
    <br>
    <button type="submit" name="ReserveNow">Reserve Now</button>
</form>


</body>
</html>

